workflow actions to match structure

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -34,17 +34,14 @@ jobs:
         _branch="${GITHUB_BASE_REF}"
         case "${_branch}" in
           "prod")
-            _tfdir=terraform/prod
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_PROD}"
+            _tfdir=terraform
             ;;
           "qa")
-            _tfdir=terraform/qa
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_QA}"
+            _tfdir=terraform
             ;;
           *)
-            _tfdir=terraform/dev
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_DEV}"
-            ;;
+            echo "ERROR: Unknown target branch: ${_branch}"
+            exit 1
         esac
         cd ${_tfdir}
         echo "***Running terraform lint***"
@@ -65,21 +62,23 @@ jobs:
         echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
         source tfvars
         _branch="${GITHUB_BASE_REF}"
+        _tfdir=terraform
+        export TF_VAR_pingone_environment_name="${_branch}"
         case "${_branch}" in
           "prod")
-            _tfdir=terraform/prod
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_PROD}"
+            _stateKey=${TF_VAR_tf_state_key_prefix}/prod/terraform.tfstate
             ;;
           "qa")
-            _tfdir=terraform/qa
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_QA}"
+            _stateKey=${TF_VAR_tf_state_key_prefix}/qa/terraform.tfstate
             ;;
           *)
-            _tfdir=terraform/dev
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_DEV}"
-            ;;
+            echo "ERROR: Unknown target branch: ${_branch}"
+            exit 1
         esac
-        terraform -chdir=${_tfdir} init
+        terraform -chdir=${_tfdir} init \
+          -backend-config="bucket=$TF_VAR_tf_state_bucket" \
+          -backend-config="region=$TF_VAR_tf_state_region" \
+          -backend-config="key=${_stateKey}"
         echo "***Running terraform validate***"
         terraform -chdir=${_tfdir} validate
         
@@ -111,20 +110,22 @@ jobs:
         echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
         source tfvars
         _branch="${GITHUB_BASE_REF}"
+        _tfdir=terraform
+        export TF_VAR_pingone_environment_name="${_branch}"
         case "${_branch}" in
           "prod")
-            _tfdir=terraform/prod
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_PROD}"
+            _stateKey="${TF_VAR_tf_state_key_prefix}/prod/terraform.tfstate"
             ;;
           "qa")
-            _tfdir=terraform/qa
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_QA}"
+            _stateKey="${TF_VAR_tf_state_key_prefix}/qa/terraform.tfstate"
             ;;
           *)
-            _tfdir=terraform/dev
-            export TF_VAR_pingone_target_environment_id="${PINGONE_TARGET_ENVIRONMENT_ID_DEV}"
-            ;;
+            echo "ERROR: Unknown target branch: ${_branch}"
+            exit 1
         esac
-        terraform -chdir=${_tfdir} init
+        terraform -chdir=${_tfdir} init \
+          -backend-config="bucket=$TF_VAR_tf_state_bucket" \
+          -backend-config="region=$TF_VAR_tf_state_region" \
+          -backend-config="key=${_stateKey}"
         echo "***Running terraform plan***"
         terraform -chdir=${_tfdir} plan
